name: DAST Security Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Wapiti
        run: |
          sudo apt update
          sudo apt install -y wapiti

      - name: Install Dependencies
        run: pip install requests

      - name: Run Wapiti Scan
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scan.py  # Ensure this matches your Python file name
