name: DAST Security Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Wapiti
        id: cache-wapiti
        uses: actions/cache@v4
        with:
          path: /usr/bin/wapiti  # Cache Wapiti binary
          key: wapiti-cache-v1
          restore-keys: wapiti-cache-

      - name: Install Wapiti (if not cached)
        if: steps.cache-wapiti.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y wapiti

      - name: Install Python Dependencies
        run: pip install requests

      - name: Run Wapiti Scan and Send Report
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scan.py

      - name: Upload Report to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wapiti-reports
          path: report.html/
